services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - redis-net
    volumes:
      - redis_insight:/db

volumes:
  redis-data:
  redis_insight:
networks:
  redis-net:
